### ISSUE TITLE
Round-trip NULLs don't quite work

### ISSUE THREAD

**Issue by apoliakov** [Paradigm4/SciDBR#144]
When loading numeric NA values to DB and back, things work fine. But with strings, NAs get loaded up as values "null" when AIO is used:

```R
> a = c('a', 'b', NA)
> b = c(1, NA, 3)
> c = data.frame(a, b)
> d = as.scidb(DB, c)
store(project(apply(aio_input('/data/scidb_data/0/0/shim_input_buf_HUsJX2','num_attributes=2','chunk_size=100000'),a, a0,b, dcast(a1, double(null))),a,b),R_array8ce502156b91485209028891185135) 
Query time 0.298 
> as.R(d)
apply(R_array8ce502156b91485209028891185135, tuple_no_1,tuple_no,dst_instance_id_1,dst_instance_id,src_instance_id_1,src_instance_id) 
Query time 0.051 
remove(R_array8ce73229e771485209028891185135) 
Query time 0.039 
Data transfer time 0.138 
  R buffer  123 / 123  bytes parsing time 0.001 
  R rbind/df assembly time 0.001 
Total R parsing time 0.002 
  tuple_no dst_instance_id src_instance_id    a  b
1        0               0               0    a  1
2        1               0               0    b NA
3        2               0               0 null  3
> as.R(d)$a
apply(R_array8ce502156b91485209028891185135, tuple_no_1,tuple_no,dst_instance_id_1,dst_instance_id,src_instance_id_1,src_instance_id) 
Query time 0.05 
Data transfer time 0.085 
  R buffer  123 / 123  bytes parsing time 0 
  R rbind/df assembly time 0.002 
Total R parsing time 0.002 
[1] "a"    "b"    "null"
```

So this would work if we change the AFL to replace
```a, a0,```
with 
```a, iif(a0 ='null', null, a0),```

Unfortunately, a user may supply a value "null" and not be aware that it's converted into a NULL but that's essentially unavoidable as some kind of sequence to represent NULLs is needed - empty string, "NA", "null" - take your pick. R's `read.table` routine has the same problem and lets the user specify an `na.strings=` argument.

**Comment by bwlewis** [comment]
This should be fixed in devel.

**Comment by rvernica** [comment]
This issue is still present in both `devel` and `master`.

Here is an example:
* Without `accelerated_io_tools` (correct):
    ```R
    > as.R(as.scidb(db, data.frame(x = c("x", NA))), only_attributes = TRUE)
         x
    1    x
    2 <NA>
    ```
* With `accelerated_io_tools` (incorrect):
   ```R
    > as.R(as.scidb(db, data.frame(x = c("x", NA))), only_attributes = TRUE)
         x
    1    x
    2 null
   ```

In both cases, SciDBR, uploaads the following `TSV` formatted file:
```
X
null
```

The following AFL queries are used for for the two cases:
* Without `accelerated_io_tools` (correct):
    ```Python
    AFL% input(<x:string>[i=1:2,10000,0], '/tmp/foo', -2, 'tsv');
    {i} x
    {1} 'X'
    {2} null
    ```
* With `accelerated_io_tools` (incorrect):
   ```Python
    AFL% project(apply(aio_input('/foo','num_attributes=1'),x, a0),x);
    {tuple_no,dst_instance_id,src_instance_id} x
    {0,0,0} 'X'
    {1,0,0} 'null'
   ```

The two operators, `input` and `aio_input`, interpret the *"null"* character sequence differently.

An example like the one above is used in the [test suite](https://github.com/Paradigm4/SciDBR/blob/6430d7442087261f2056b626b32bf98c611afdb7/tests/a.R#L50), so if the test suite is run on a setup with the `accelerated_io_tools` plugin enabled, the test suite fails. The error is:
```
* checking tests ...
  Running ‘a.R’
 ERROR
Running the tests in ‘tests/a.R’ failed.
Last 13 lines of output:
  check(a = as.R(db$op_count(x))$count, b = nrow(as.R(x, only_attributes = TRUE)))
  check(a = as.R(db$op_count(x))$count, b = nrow(as.R(a)))
  check(a = as.R(db$op_count(x))$count, b = nrow(as.R(a)))
  check(a = 1:5, b = as.R(as.scidb(db, 1:5))[, 2])
  check(a = x, b = matrix(as.R(as.scidb(db, x))[, 3], 10, byrow = TRUE))
  check(a = x, b = Matrix::sparseMatrix(i = y$i + 1, j = y$j +
      1, x = y$val))
  check(a = df, b = as.R(sdf, only_attributes = TRUE))
  check(a = df, b = as.R(x, only_attributes = TRUE))
  Error: a and b are not equal:
    Component "x1": 'is.NA' value mismatch: 0 in current 1 in target
```

**Comment by ksens** [comment]
Decision taken was

- use `input` by default in all cases 
- have a flag in `as.scidb()` like `use_aio_input=TRUE` to choose `aio_input` instead of `input`
